artifact_uri: file:///Users/christianoviedo/Desktop/ciencia_datos/diplo_datos_repos/diplo_datos_git_practicos_new/optativas/aprendizaje_profundo/practico/mlruns/1/3cebdb77e9414e53bf950a3d34f914b3/artifacts
end_time: 1643660251744
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 3cebdb77e9414e53bf950a3d34f914b3
run_uuid: 3cebdb77e9414e53bf950a3d34f914b3
source_name: ''
source_type: 4
source_version: ''
start_time: 1643660210932
status: 3
tags: []
user_id: christianoviedo
