artifact_uri: file:///Users/christianoviedo/Desktop/ciencia_datos/diplo_datos_repos/diplo_datos_git_practicos_new/optativas/aprendizaje_profundo/practico/mlruns/1/b96ed3d6b69942f9b2954894c3067c4b/artifacts
end_time: 1643661738874
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: b96ed3d6b69942f9b2954894c3067c4b
run_uuid: b96ed3d6b69942f9b2954894c3067c4b
source_name: ''
source_type: 4
source_version: ''
start_time: 1643661696949
status: 3
tags: []
user_id: christianoviedo
