artifact_uri: file:///Users/christianoviedo/Desktop/ciencia_datos/diplo_datos_repos/diplo_datos_git_practicos_new/optativas/aprendizaje_profundo/practico/mlruns/1/9695b758d1db45cf85c3fcc1ecba910c/artifacts
end_time: 1643659738981
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 9695b758d1db45cf85c3fcc1ecba910c
run_uuid: 9695b758d1db45cf85c3fcc1ecba910c
source_name: ''
source_type: 4
source_version: ''
start_time: 1643659697199
status: 3
tags: []
user_id: christianoviedo
