artifact_location: file:///Users/christianoviedo/Desktop/ciencia_datos/diplo_datos_repos/diplo_datos_git_practicos_new/optativas/aprendizaje_profundo/practico/mlruns/1
experiment_id: '1'
lifecycle_stage: active
name: diplodatos.spanish
