artifact_uri: file:///Users/christianoviedo/Desktop/ciencia_datos/diplo_datos_repos/diplo_datos_git_practicos_new/optativas/aprendizaje_profundo/practico/mlruns/1/3d2118aa155b4ecd8812137459f791b8/artifacts
end_time: 1643661531913
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 3d2118aa155b4ecd8812137459f791b8
run_uuid: 3d2118aa155b4ecd8812137459f791b8
source_name: ''
source_type: 4
source_version: ''
start_time: 1643661485254
status: 3
tags: []
user_id: christianoviedo
