artifact_uri: file:///Users/christianoviedo/Desktop/ciencia_datos/diplo_datos_repos/diplo_datos_git_practicos_new/optativas/aprendizaje_profundo/practico/mlruns/1/a454a0a03a244cb4ad92c33f7428eaf9/artifacts
end_time: 1643660375707
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: a454a0a03a244cb4ad92c33f7428eaf9
run_uuid: a454a0a03a244cb4ad92c33f7428eaf9
source_name: ''
source_type: 4
source_version: ''
start_time: 1643660335187
status: 3
tags: []
user_id: christianoviedo
