artifact_uri: file:///Users/christianoviedo/Desktop/ciencia_datos/diplo_datos_repos/diplo_datos_git_practicos_new/optativas/aprendizaje_profundo/practico/mlruns/1/07b39d54ba1043568a93a12f896536c7/artifacts
end_time: 1643662329254
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 07b39d54ba1043568a93a12f896536c7
run_uuid: 07b39d54ba1043568a93a12f896536c7
source_name: ''
source_type: 4
source_version: ''
start_time: 1643662241466
status: 4
tags: []
user_id: christianoviedo
