artifact_uri: file:///Users/christianoviedo/Desktop/ciencia_datos/diplo_datos_repos/diplo_datos_git_practicos_new/optativas/aprendizaje_profundo/practico/mlruns/1/d58a42af60ef481393b780efebdad9fe/artifacts
end_time: 1643662432083
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: d58a42af60ef481393b780efebdad9fe
run_uuid: d58a42af60ef481393b780efebdad9fe
source_name: ''
source_type: 4
source_version: ''
start_time: 1643662395329
status: 4
tags: []
user_id: christianoviedo
