artifact_uri: file:///Users/christianoviedo/Desktop/ciencia_datos/diplo_datos_repos/diplo_datos_git_practicos_new/optativas/aprendizaje_profundo/practico/mlruns/1/df74f6d22172496eac8ce0d2d8dd6b5f/artifacts
end_time: 1643661590055
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: df74f6d22172496eac8ce0d2d8dd6b5f
run_uuid: df74f6d22172496eac8ce0d2d8dd6b5f
source_name: ''
source_type: 4
source_version: ''
start_time: 1643661537726
status: 3
tags: []
user_id: christianoviedo
