artifact_uri: file:///Users/christianoviedo/Desktop/ciencia_datos/diplo_datos_repos/diplo_datos_git_practicos_new/optativas/aprendizaje_profundo/practico/mlruns/1/1d607f59af2f4ac0b1925b96f93125dd/artifacts
end_time: 1643660323310
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 1d607f59af2f4ac0b1925b96f93125dd
run_uuid: 1d607f59af2f4ac0b1925b96f93125dd
source_name: ''
source_type: 4
source_version: ''
start_time: 1643660282494
status: 3
tags: []
user_id: christianoviedo
