artifact_uri: file:///Users/christianoviedo/Desktop/ciencia_datos/diplo_datos_repos/diplo_datos_git_practicos_new/optativas/aprendizaje_profundo/practico/mlruns/1/3bd14e38dd884c47bc8688aff7cfac27/artifacts
end_time: 1643662521984
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 3bd14e38dd884c47bc8688aff7cfac27
run_uuid: 3bd14e38dd884c47bc8688aff7cfac27
source_name: ''
source_type: 4
source_version: ''
start_time: 1643662445983
status: 4
tags: []
user_id: christianoviedo
