artifact_uri: file:///Users/christianoviedo/Desktop/ciencia_datos/diplo_datos_repos/diplo_datos_git_practicos_new/optativas/aprendizaje_profundo/practico/mlruns/1/a3db1bf13c4c4225bf5c65bd46a54468/artifacts
end_time: 1643662048467
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: a3db1bf13c4c4225bf5c65bd46a54468
run_uuid: a3db1bf13c4c4225bf5c65bd46a54468
source_name: ''
source_type: 4
source_version: ''
start_time: 1643662007940
status: 3
tags: []
user_id: christianoviedo
