artifact_uri: file:///Users/christianoviedo/Desktop/ciencia_datos/diplo_datos_repos/diplo_datos_git_practicos_new/optativas/aprendizaje_profundo/practico/mlruns/1/241f68ea478d4c32b9eb0950c598be30/artifacts
end_time: 1643662385562
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 241f68ea478d4c32b9eb0950c598be30
run_uuid: 241f68ea478d4c32b9eb0950c598be30
source_name: ''
source_type: 4
source_version: ''
start_time: 1643662339439
status: 4
tags: []
user_id: christianoviedo
