artifact_uri: file:///Users/christianoviedo/Desktop/ciencia_datos/diplo_datos_repos/diplo_datos_git_practicos_new/optativas/aprendizaje_profundo/practico/mlruns/1/44488153555d4d8e80c6210f5018db62/artifacts
end_time: 1643661678129
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 44488153555d4d8e80c6210f5018db62
run_uuid: 44488153555d4d8e80c6210f5018db62
source_name: ''
source_type: 4
source_version: ''
start_time: 1643661595773
status: 3
tags: []
user_id: christianoviedo
